version: '2'
services:
  apache:
    image: tcoder/m2-apache
    ports:
      - "80:80"
      - "443:443"
      - "9001:9000"
    volumes:
      - m2-apache-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 remote_connect_back=0"      
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - m2-apache-network

  db:
    image: mariadb:10.4
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - m2-apache-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - m2-apache-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - m2-apache-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - m2-apache-network

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: m2-apache_elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=127.0.0.1:9300
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - m2-apache-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - m2-apache-network

networks:
  m2-apache-network:
    driver: bridge

volumes:
  m2-apache-sync:
    external: true
  dbdata:
    driver: local
  esdata:
    driver: local
